[project]
name = "nanotron"
version = "0.4"
description = "Minimalistic Large Language Model Training and Finetuning"
authors = [
    {name = "Nouamane Tazi", email="nouamane@huggingface.co"},
    {name = "Thomas Wang", email="thomas.wang@huggingface.co"},
    {name = "Kunhao Zheng", email="kunhao@huggingface.co"},
    {name = "Thomas Wolf", email="thomas@huggingface.co"},
]
readme = "README.md"
requires-python = ">=3.10,<3.12"
classifiers = [
    "Topic :: Software Development"
]
dependencies = [
    "torch>=2.11.0,<2.12",
    "pyyaml>=6.0.2",
    "numpy>=1.26.4,<2",
    "packaging>=25.0",
    "safetensors>=0.6.2",
    "dacite>=1.9.2",
    "tqdm>=4.67.1",
    "datasets>=4.0.0",
    "torchtyping>=0.1.5",
    "wandb>=0.21.3,<0.22",
]

[tool.setuptools.packages.find]
where = ["src"]  # list of folders that contain the packages (["."] by default)

[tool.ruff]
line-length = 119
ignore = ["C901","E501"] # E501 ignores length violation handled by black
select = ["C","E","F","I","W"]
ignore-init-module-imports = true

[project.optional-dependencies]
dev = [
    "pre-commit",
    "pylint"
]

test = [
    "pytest",
    "pytest-xdist"
]

fast-modeling = [
    "flash-attn>=2.8.3,<3.0.0",
    # FlashAttention on the cluster should be installed from a local wheel.
    "ninja>=1.13.0",
    "psutil>=7.0.0",
    "triton>=3.6.0",
]

nanosets = [
    "transformers>=4.57.3,<5",
    "datatrove[io,processing]>=0.5.0,<0.6.0",
    "numba>=0.61.2,<0.62",
    "pyarrow>=21.0.0",
    "pandas>=2.3.2",
    "orjson>=3.11.3",
]

eval = [
    "accelerate>=1.11.0,<2",
    "evaluate>=0.4.6,<0.5",
    "lm_eval @ git+https://github.com/aynetdia/lm-evaluation-harness.git@boldt",
    "protobuf>=6.32.0,<7",
    "sentencepiece>=0.2.1",
]

s3 = [
    "boto3",
    "s3fs",
    "s5cmd",
]

[build-system]
requires = [
    "setuptools",
]

[pytest]
norecursedirs="tests/helpers"
